# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack OOmiNet --no-build 

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest

    - name: NuGet push
      uses: edumserrano/nuget-push@v1.2.2
      with:
        api-key: oy2fi4iy67mfv77sib2aguty7b2uxrnu7ddcsc6yaoca7m
        nuget-package: "**/*.nupkg"
